x0=-960
x1=-820
y0=55
y1=104
z0=-280
z1=-145
palette.0=minecraft:unknown
palette.1=minecraft:diorite
palette.2=minecraft:gravel
palette.3=minecraft:stone
palette.4=minecraft:copper_ore
palette.5=minecraft:granite
palette.6=minecraft:andesite
palette.7=minecraft:dirt
palette.8=minecraft:gold_ore
palette.9=minecraft:iron_ore
palette.10=minecraft:coal_ore
palette.11=minecraft:air
palette.12=minecraft:terracotta
palette.13=minecraft:orange_terracotta
palette.14=minecraft:light_gray_terracotta
palette.15=minecraft:white_terracotta
palette.16=minecraft:red_terracotta
palette.17=minecraft:brown_terracotta
palette.18=minecraft:dead_bush
palette.19=minecraft:clay
palette.20=minecraft:big_dripleaf_stem
palette.21=minecraft:big_dripleaf
palette.22=minecraft:cave_vines
palette.23=minecraft:cave_vines_plant
palette.24=minecraft:glow_lichen
palette.25=minecraft:lapis_ore
palette.26=minecraft:lava
palette.27=minecraft:cave_air
palette.28=minecraft:grass_block
palette.29=minecraft:coarse_dirt
palette.30=minecraft:moss_block
palette.31=minecraft:moss_carpet
palette.32=minecraft:vine
palette.33=minecraft:short_grass
palette.34=minecraft:azalea
palette.35=minecraft:tall_grass
palette.36=minecraft:flowering_azalea
palette.37=minecraft:spore_blossom
palette.38=minecraft:oak_log
palette.39=minecraft:water
palette.40=minecraft:red_sand
palette.41=minecraft:oak_leaves
palette.42=minecraft:yellow_terracotta
palette.43=minecraft:obsidian
palette.44=minecraft:red_sandstone
palette.45=minecraft:glowstone
palette.46=minecraft:bubble_column
palette.47=minecraft:sand
palette.48=minecraft:tall_seagrass
palette.49=minecraft:seagrass
palette.50=minecraft:sugar_cane
palette.51=minecraft:netherrack
palette.52=minecraft:wall_torch
palette.53=minecraft:torch
palette.54=minecraft:prismarine
palette.55=minecraft:glass
