import type { GlideRecordingSample } from './calibration'

import { describe, expect, it } from 'vitest'

import { computeGlideResiduals, dedupeGlideRecording, startGlideAudit } from './calibration'
import { FLIGHT_PROFILE_1_21_1 } from './profile'
import { simulateFlight } from './simulation'

describe('computeGlideResiduals (E-01)', () => {
  function syntheticRecording(pitchDeg: number): GlideRecordingSample[] {
    // The recording is generated by the model itself: this test exercises the
    // tick-mark mapping and error accounting, not the physics (the physics
    // meets reality only in the live E-01 run).
    const trajectory = simulateFlight(FLIGHT_PROFILE_1_21_1, {
      position: { x: 0, y: 100, z: 0 },
      velocity: { x: 0.8, y: -0.05, z: 0 },
      yaw: 0,
      pitch: pitchDeg,
      rocketTicksRemaining: 0,
      onGround: false,
      inWater: false,
    }, Array.from({ length: 46 }, () => ({ yaw: 0, pitch: pitchDeg })))
    return trajectory.samples.map((sample, index) => ({
      at: (index + 1) * 50,
      position: { ...sample.position },
      motion: { ...sample.velocity },
      yaw: 0,
      pitch: pitchDeg,
    }))
  }

  it('reports near-zero residuals when the recording matches the model inputs', () => {
    const report = computeGlideResiduals(FLIGHT_PROFILE_1_21_1, syntheticRecording(-3), { yaw: 0, pitch: -3 })
    expect(report.notes).toEqual([])
    expect(report.points.map(point => point.tick)).toEqual([10, 20, 40])
    for (const point of report.points) {
      expect(point.sampleJitterMs).toBe(0)
      expect(point.errorBlocks).toBeLessThan(0.5)
    }
  })

  it('maps a tick mark to the nearest recorded sample when the capture jitters', () => {
    const recording = syntheticRecording(-3).map(sample => ({ ...sample, at: sample.at + 12 }))
    const report = computeGlideResiduals(FLIGHT_PROFILE_1_21_1, recording, { yaw: 0, pitch: -3 })
    for (const point of report.points)
      expect(point.sampleJitterMs).toBeLessThanOrEqual(25)
  })

  it('notes a too-short recording instead of inventing points', () => {
    const report = computeGlideResiduals(FLIGHT_PROFILE_1_21_1, syntheticRecording(-3).slice(0, 4), { yaw: 0, pitch: -3 })
    expect(report.points).toEqual([])
    expect(report.notes[0]).toContain('is not comparable')
  })

  it('collapses repeated reads of the same tick before comparing', () => {
    // ROOT CAUSE (live E-01, 2026-09-18):
    //
    // The bridge answers repeated `get_self` calls from the same client tick, so
    // a fast poll returns byte-identical runs: the pitch -3 run 3 capture held
    // 1148 identical pairs out of 1748 samples. Treating each read as its own
    // sample pushed the tick-20 mark five ticks off and reported 0.76 blocks of
    // error that the model did not have.
    //
    // We fixed this by keeping only reads whose state actually changed.
    const recording = syntheticRecording(-3)
    const repeated = recording.flatMap(sample => [sample, { ...sample, at: sample.at + 5 }])
    expect(repeated.length).toBe(recording.length * 2)
    const distinct = dedupeGlideRecording(repeated)
    expect(distinct.length).toBe(recording.length)
    expect(distinct[1]!.at).toBe(recording[1]!.at)
  })

  it('keeps a repeated read when the state actually changed', () => {
    const recording = syntheticRecording(-3)
    const moved = { ...recording[1]!, at: recording[1]!.at + 5, position: { ...recording[1]!.position, x: recording[1]!.position.x + 0.01 } }
    const distinct = dedupeGlideRecording([recording[0]!, recording[1]!, moved, recording[2]!])
    expect(distinct.length).toBe(4)
  })

  it('drops the launch transient from the audit window', () => {
    const recording = syntheticRecording(-3)
    expect(startGlideAudit(recording, 20).length).toBe(recording.length - 20)
    expect(startGlideAudit(recording, 0)).toBe(recording)
  })
})
