x0=-1010
x1=-900
y0=55
y1=104
z0=-185
z1=-45
palette.0=minecraft:unknown
palette.1=minecraft:stone
palette.2=minecraft:andesite
palette.3=minecraft:copper_ore
palette.4=minecraft:granite
palette.5=minecraft:coal_ore
palette.6=minecraft:diorite
palette.7=minecraft:lapis_ore
palette.8=minecraft:clay
palette.9=minecraft:iron_ore
palette.10=minecraft:vine
palette.11=minecraft:dirt
palette.12=minecraft:air
palette.13=minecraft:gravel
palette.14=minecraft:grass_block
palette.15=minecraft:jungle_log
palette.16=minecraft:oak_leaves
palette.17=minecraft:fern
palette.18=minecraft:short_grass
palette.19=minecraft:oak_log
palette.20=minecraft:jungle_leaves
palette.21=minecraft:glow_lichen
palette.22=minecraft:mossy_cobblestone
palette.23=minecraft:cobblestone
palette.24=minecraft:cobblestone_stairs
palette.25=minecraft:cocoa
palette.26=minecraft:melon
palette.27=minecraft:dandelion
palette.28=minecraft:water
palette.29=minecraft:seagrass
palette.30=minecraft:tall_seagrass
palette.31=minecraft:sand
palette.32=minecraft:tall_grass
palette.33=minecraft:bamboo
palette.34=minecraft:light_blue_wool
palette.35=minecraft:gold_ore
palette.36=minecraft:terracotta
palette.37=minecraft:orange_terracotta
palette.38=minecraft:light_gray_terracotta
palette.39=minecraft:white_terracotta
palette.40=minecraft:red_terracotta
palette.41=minecraft:brown_terracotta
palette.42=minecraft:dead_bush
palette.43=minecraft:obsidian
palette.44=minecraft:poppy
palette.45=minecraft:moss_block
palette.46=minecraft:red_sand
palette.47=minecraft:coarse_dirt
palette.48=minecraft:yellow_terracotta
palette.49=minecraft:glowstone
palette.50=minecraft:podzol
palette.51=minecraft:red_sandstone
